export interface EmojiEntry {
  emoji: string;
  name: string;
  category: "smileys" | "objects" | "symbols" | "animals" | "food" | "travel" | "activities";
}

export type EntityType = "project" | "agent" | "skill" | "team";

export const DEFAULT_EMOJIS: Record<EntityType, string> = {
  project: "📦",
  agent: "🤖",
  skill: "⚡",
  team: "👥",
};

export const EMOJI_DATA: EmojiEntry[] = [
  // Smileys (100 emojis)
  { emoji: "😀", name: "grinning face", category: "smileys" },
  { emoji: "😁", name: "beaming face with smiling eyes", category: "smileys" },
  { emoji: "😂", name: "face with tears of joy", category: "smileys" },
  { emoji: "🤣", name: "rolling on the floor laughing", category: "smileys" },
  { emoji: "😃", name: "grinning face with big eyes", category: "smileys" },
  { emoji: "😄", name: "grinning face with smiling eyes", category: "smileys" },
  { emoji: "😅", name: "grinning face with sweat", category: "smileys" },
  { emoji: "😆", name: "grinning squinting face", category: "smileys" },
  { emoji: "😉", name: "winking face", category: "smileys" },
  { emoji: "😊", name: "smiling face with smiling eyes", category: "smileys" },
  { emoji: "😇", name: "smiling face with halo", category: "smileys" },
  { emoji: "🙂", name: "slightly smiling face", category: "smileys" },
  { emoji: "🙃", name: "upside down face", category: "smileys" },
  { emoji: "😋", name: "face savoring food", category: "smileys" },
  { emoji: "😌", name: "relieved face", category: "smileys" },
  { emoji: "😍", name: "smiling face with heart eyes", category: "smileys" },
  { emoji: "🥰", name: "smiling face with hearts", category: "smileys" },
  { emoji: "😘", name: "face blowing a kiss", category: "smileys" },
  { emoji: "😗", name: "kissing face", category: "smileys" },
  { emoji: "😙", name: "kissing face with smiling eyes", category: "smileys" },
  { emoji: "😚", name: "kissing face with closed eyes", category: "smileys" },
  { emoji: "😜", name: "winking face with tongue", category: "smileys" },
  { emoji: "🤪", name: "zany face", category: "smileys" },
  { emoji: "😝", name: "squinting face with tongue", category: "smileys" },
  { emoji: "🤑", name: "money mouth face", category: "smileys" },
  { emoji: "🤗", name: "smiling face with open hands", category: "smileys" },
  { emoji: "🤭", name: "face with hand over mouth", category: "smileys" },
  { emoji: "🤫", name: "shushing face", category: "smileys" },
  { emoji: "🤔", name: "thinking face", category: "smileys" },
  { emoji: "🤐", name: "zipper mouth face", category: "smileys" },
  { emoji: "🤨", name: "face with raised eyebrow", category: "smileys" },
  { emoji: "😐", name: "neutral face", category: "smileys" },
  { emoji: "😑", name: "expressionless face", category: "smileys" },
  { emoji: "😶", name: "face without mouth", category: "smileys" },
  { emoji: "😏", name: "smirking face", category: "smileys" },
  { emoji: "😒", name: "unamused face", category: "smileys" },
  { emoji: "🙄", name: "face with rolling eyes", category: "smileys" },
  { emoji: "😬", name: "grimacing face", category: "smileys" },
  { emoji: "🤥", name: "lying face", category: "smileys" },
  { emoji: "😔", name: "pensive face", category: "smileys" },
  { emoji: "😪", name: "sleepy face", category: "smileys" },
  { emoji: "🤤", name: "drooling face", category: "smileys" },
  { emoji: "😴", name: "sleeping face", category: "smileys" },
  { emoji: "😷", name: "face with medical mask", category: "smileys" },
  { emoji: "🤒", name: "face with thermometer", category: "smileys" },
  { emoji: "🤕", name: "face with head bandage", category: "smileys" },
  { emoji: "🤢", name: "nauseated face", category: "smileys" },
  { emoji: "🤮", name: "face vomiting", category: "smileys" },
  { emoji: "🤧", name: "sneezing face", category: "smileys" },
  { emoji: "🥵", name: "hot face", category: "smileys" },
  { emoji: "🥶", name: "cold face", category: "smileys" },
  { emoji: "😎", name: "smiling face with sunglasses", category: "smileys" },
  { emoji: "🤓", name: "nerd face", category: "smileys" },
  { emoji: "🧐", name: "face with monocle", category: "smileys" },
  { emoji: "😕", name: "confused face", category: "smileys" },
  { emoji: "😟", name: "worried face", category: "smileys" },
  { emoji: "🙁", name: "slightly frowning face", category: "smileys" },
  { emoji: "☹️", name: "frowning face", category: "smileys" },
  { emoji: "😮", name: "face with open mouth", category: "smileys" },
  { emoji: "😯", name: "hushed face", category: "smileys" },
  { emoji: "😲", name: "astonished face", category: "smileys" },
  { emoji: "😳", name: "flushed face", category: "smileys" },
  { emoji: "🥺", name: "pleading face", category: "smileys" },
  { emoji: "😦", name: "frowning face with open mouth", category: "smileys" },
  { emoji: "😧", name: "anguished face", category: "smileys" },
  { emoji: "😨", name: "fearful face", category: "smileys" },
  { emoji: "😰", name: "anxious face with sweat", category: "smileys" },
  { emoji: "😥", name: "sad but relieved face", category: "smileys" },
  { emoji: "😢", name: "crying face", category: "smileys" },
  { emoji: "😭", name: "loudly crying face", category: "smileys" },
  { emoji: "😱", name: "face screaming in fear", category: "smileys" },
  { emoji: "😖", name: "confounded face", category: "smileys" },
  { emoji: "😣", name: "persevering face", category: "smileys" },
  { emoji: "😞", name: "disappointed face", category: "smileys" },
  { emoji: "😓", name: "downcast face with sweat", category: "smileys" },
  { emoji: "😩", name: "weary face", category: "smileys" },
  { emoji: "😫", name: "tired face", category: "smileys" },
  { emoji: "🥱", name: "yawning face", category: "smileys" },
  { emoji: "😤", name: "face with steam from nose", category: "smileys" },
  { emoji: "😡", name: "pouting face", category: "smileys" },
  { emoji: "😠", name: "angry face", category: "smileys" },
  { emoji: "🤬", name: "face with symbols on mouth", category: "smileys" },
  { emoji: "😈", name: "smiling face with horns", category: "smileys" },
  { emoji: "👿", name: "angry face with horns", category: "smileys" },
  { emoji: "💀", name: "skull", category: "smileys" },
  { emoji: "☠️", name: "skull and crossbones", category: "smileys" },
  { emoji: "💩", name: "pile of poo", category: "smileys" },
  { emoji: "🤡", name: "clown face", category: "smileys" },
  { emoji: "👹", name: "ogre", category: "smileys" },
  { emoji: "👺", name: "goblin", category: "smileys" },
  { emoji: "👻", name: "ghost", category: "smileys" },
  { emoji: "👽", name: "alien", category: "smileys" },
  { emoji: "👾", name: "alien monster", category: "smileys" },
  { emoji: "🤖", name: "robot", category: "smileys" },
  { emoji: "🎃", name: "jack o lantern", category: "smileys" },
  { emoji: "💋", name: "kiss mark", category: "smileys" },
  { emoji: "💯", name: "hundred points", category: "smileys" },
  { emoji: "💢", name: "anger symbol", category: "smileys" },
  { emoji: "💥", name: "collision", category: "smileys" },

  // Objects (120 emojis)
  { emoji: "📱", name: "mobile phone", category: "objects" },
  { emoji: "💻", name: "laptop", category: "objects" },
  { emoji: "⌨️", name: "keyboard", category: "objects" },
  { emoji: "🖥️", name: "desktop computer", category: "objects" },
  { emoji: "🖨️", name: "printer", category: "objects" },
  { emoji: "🖱️", name: "computer mouse", category: "objects" },
  { emoji: "🖲️", name: "trackball", category: "objects" },
  { emoji: "💾", name: "floppy disk", category: "objects" },
  { emoji: "💿", name: "optical disk", category: "objects" },
  { emoji: "📀", name: "dvd", category: "objects" },
  { emoji: "📼", name: "videocassette", category: "objects" },
  { emoji: "📷", name: "camera", category: "objects" },
  { emoji: "📹", name: "video camera", category: "objects" },
  { emoji: "📺", name: "television", category: "objects" },
  { emoji: "📻", name: "radio", category: "objects" },
  { emoji: "🎥", name: "movie camera", category: "objects" },
  { emoji: "🎬", name: "clapper board", category: "objects" },
  { emoji: "📞", name: "telephone receiver", category: "objects" },
  { emoji: "☎️", name: "telephone", category: "objects" },
  { emoji: "📟", name: "pager", category: "objects" },
  { emoji: "📠", name: "fax machine", category: "objects" },
  { emoji: "⏰", name: "alarm clock", category: "objects" },
  { emoji: "⏱️", name: "stopwatch", category: "objects" },
  { emoji: "⏲️", name: "timer clock", category: "objects" },
  { emoji: "⌚", name: "watch", category: "objects" },
  { emoji: "📡", name: "satellite antenna", category: "objects" },
  { emoji: "🔋", name: "battery", category: "objects" },
  { emoji: "🔌", name: "electric plug", category: "objects" },
  { emoji: "💡", name: "light bulb", category: "objects" },
  { emoji: "🔦", name: "flashlight", category: "objects" },
  { emoji: "🕯️", name: "candle", category: "objects" },
  { emoji: "🪔", name: "diya lamp", category: "objects" },
  { emoji: "💰", name: "money bag", category: "objects" },
  { emoji: "💴", name: "yen banknote", category: "objects" },
  { emoji: "💵", name: "dollar banknote", category: "objects" },
  { emoji: "💶", name: "euro banknote", category: "objects" },
  { emoji: "💷", name: "pound banknote", category: "objects" },
  { emoji: "💸", name: "money with wings", category: "objects" },
  { emoji: "💳", name: "credit card", category: "objects" },
  { emoji: "💎", name: "gem stone", category: "objects" },
  { emoji: "⚖️", name: "balance scale", category: "objects" },
  { emoji: "🔧", name: "wrench", category: "objects" },
  { emoji: "🔨", name: "hammer", category: "objects" },
  { emoji: "⚒️", name: "hammer and pick", category: "objects" },
  { emoji: "🛠️", name: "hammer and wrench", category: "objects" },
  { emoji: "⛏️", name: "pick", category: "objects" },
  { emoji: "🔩", name: "nut and bolt", category: "objects" },
  { emoji: "⚙️", name: "gear", category: "objects" },
  { emoji: "🧰", name: "toolbox", category: "objects" },
  { emoji: "🔫", name: "water pistol", category: "objects" },
  { emoji: "💣", name: "bomb", category: "objects" },
  { emoji: "🔪", name: "kitchen knife", category: "objects" },
  { emoji: "🗡️", name: "dagger", category: "objects" },
  { emoji: "⚔️", name: "crossed swords", category: "objects" },
  { emoji: "🛡️", name: "shield", category: "objects" },
  { emoji: "🚬", name: "cigarette", category: "objects" },
  { emoji: "⚰️", name: "coffin", category: "objects" },
  { emoji: "⚱️", name: "funeral urn", category: "objects" },
  { emoji: "🏺", name: "amphora", category: "objects" },
  { emoji: "🔮", name: "crystal ball", category: "objects" },
  { emoji: "📿", name: "prayer beads", category: "objects" },
  { emoji: "💈", name: "barber pole", category: "objects" },
  { emoji: "⚗️", name: "alembic", category: "objects" },
  { emoji: "🔭", name: "telescope", category: "objects" },
  { emoji: "🔬", name: "microscope", category: "objects" },
  { emoji: "🕳️", name: "hole", category: "objects" },
  { emoji: "💊", name: "pill", category: "objects" },
  { emoji: "💉", name: "syringe", category: "objects" },
  { emoji: "🩹", name: "adhesive bandage", category: "objects" },
  { emoji: "🩺", name: "stethoscope", category: "objects" },
  { emoji: "🚪", name: "door", category: "objects" },
  { emoji: "🛏️", name: "bed", category: "objects" },
  { emoji: "🛋️", name: "couch and lamp", category: "objects" },
  { emoji: "🪑", name: "chair", category: "objects" },
  { emoji: "🚽", name: "toilet", category: "objects" },
  { emoji: "🚿", name: "shower", category: "objects" },
  { emoji: "🛁", name: "bathtub", category: "objects" },
  { emoji: "🧴", name: "lotion bottle", category: "objects" },
  { emoji: "🧷", name: "safety pin", category: "objects" },
  { emoji: "🧹", name: "broom", category: "objects" },
  { emoji: "🧺", name: "basket", category: "objects" },
  { emoji: "🧻", name: "roll of paper", category: "objects" },
  { emoji: "🧼", name: "soap", category: "objects" },
  { emoji: "🧽", name: "sponge", category: "objects" },
  { emoji: "🧯", name: "fire extinguisher", category: "objects" },
  { emoji: "📦", name: "package", category: "objects" },
  { emoji: "📫", name: "closed mailbox with raised flag", category: "objects" },
  { emoji: "📪", name: "closed mailbox with lowered flag", category: "objects" },
  { emoji: "📬", name: "open mailbox with raised flag", category: "objects" },
  { emoji: "📭", name: "open mailbox with lowered flag", category: "objects" },
  { emoji: "📮", name: "postbox", category: "objects" },
  { emoji: "📯", name: "postal horn", category: "objects" },
  { emoji: "📜", name: "scroll", category: "objects" },
  { emoji: "📃", name: "page with curl", category: "objects" },
  { emoji: "📄", name: "page facing up", category: "objects" },
  { emoji: "📑", name: "bookmark tabs", category: "objects" },
  { emoji: "📊", name: "bar chart", category: "objects" },
  { emoji: "📈", name: "chart increasing", category: "objects" },
  { emoji: "📉", name: "chart decreasing", category: "objects" },
  { emoji: "📇", name: "card index", category: "objects" },
  { emoji: "🗂️", name: "card index dividers", category: "objects" },
  { emoji: "📅", name: "calendar", category: "objects" },
  { emoji: "📆", name: "tear off calendar", category: "objects" },
  { emoji: "🗒️", name: "spiral notepad", category: "objects" },
  { emoji: "🗓️", name: "spiral calendar", category: "objects" },
  { emoji: "📋", name: "clipboard", category: "objects" },
  { emoji: "📁", name: "file folder", category: "objects" },
  { emoji: "📂", name: "open file folder", category: "objects" },
  { emoji: "🗃️", name: "card file box", category: "objects" },
  { emoji: "🗄️", name: "file cabinet", category: "objects" },
  { emoji: "📚", name: "books", category: "objects" },
  { emoji: "📖", name: "open book", category: "objects" },
  { emoji: "📕", name: "closed book", category: "objects" },
  { emoji: "📗", name: "green book", category: "objects" },
  { emoji: "📘", name: "blue book", category: "objects" },
  { emoji: "📙", name: "orange book", category: "objects" },
  { emoji: "📓", name: "notebook", category: "objects" },
  { emoji: "📔", name: "notebook with decorative cover", category: "objects" },

  // Symbols (100 emojis)
  { emoji: "❤️", name: "red heart", category: "symbols" },
  { emoji: "🧡", name: "orange heart", category: "symbols" },
  { emoji: "💛", name: "yellow heart", category: "symbols" },
  { emoji: "💚", name: "green heart", category: "symbols" },
  { emoji: "💙", name: "blue heart", category: "symbols" },
  { emoji: "💜", name: "purple heart", category: "symbols" },
  { emoji: "🖤", name: "black heart", category: "symbols" },
  { emoji: "🤍", name: "white heart", category: "symbols" },
  { emoji: "🤎", name: "brown heart", category: "symbols" },
  { emoji: "💔", name: "broken heart", category: "symbols" },
  { emoji: "❣️", name: "heart exclamation", category: "symbols" },
  { emoji: "💕", name: "two hearts", category: "symbols" },
  { emoji: "💞", name: "revolving hearts", category: "symbols" },
  { emoji: "💓", name: "beating heart", category: "symbols" },
  { emoji: "💗", name: "growing heart", category: "symbols" },
  { emoji: "💖", name: "sparkling heart", category: "symbols" },
  { emoji: "💘", name: "heart with arrow", category: "symbols" },
  { emoji: "💝", name: "heart with ribbon", category: "symbols" },
  { emoji: "⭐", name: "star", category: "symbols" },
  { emoji: "🌟", name: "glowing star", category: "symbols" },
  { emoji: "✨", name: "sparkles", category: "symbols" },
  { emoji: "⚡", name: "high voltage", category: "symbols" },
  { emoji: "🔥", name: "fire", category: "symbols" },
  { emoji: "💫", name: "dizzy", category: "symbols" },
  { emoji: "☀️", name: "sun", category: "symbols" },
  { emoji: "🌤️", name: "sun behind small cloud", category: "symbols" },
  { emoji: "⛅", name: "sun behind cloud", category: "symbols" },
  { emoji: "🌥️", name: "sun behind large cloud", category: "symbols" },
  { emoji: "☁️", name: "cloud", category: "symbols" },
  { emoji: "🌦️", name: "sun behind rain cloud", category: "symbols" },
  { emoji: "🌧️", name: "cloud with rain", category: "symbols" },
  { emoji: "⛈️", name: "cloud with lightning and rain", category: "symbols" },
  { emoji: "🌩️", name: "cloud with lightning", category: "symbols" },
  { emoji: "🌨️", name: "cloud with snow", category: "symbols" },
  { emoji: "❄️", name: "snowflake", category: "symbols" },
  { emoji: "☃️", name: "snowman", category: "symbols" },
  { emoji: "⛄", name: "snowman without snow", category: "symbols" },
  { emoji: "🌬️", name: "wind face", category: "symbols" },
  { emoji: "💨", name: "dashing away", category: "symbols" },
  { emoji: "🌪️", name: "tornado", category: "symbols" },
  { emoji: "🌫️", name: "fog", category: "symbols" },
  { emoji: "🌈", name: "rainbow", category: "symbols" },
  { emoji: "☂️", name: "umbrella", category: "symbols" },
  { emoji: "☔", name: "umbrella with rain drops", category: "symbols" },
  { emoji: "⛱️", name: "umbrella on ground", category: "symbols" },
  { emoji: "❌", name: "cross mark", category: "symbols" },
  { emoji: "⭕", name: "hollow red circle", category: "symbols" },
  { emoji: "✅", name: "check mark button", category: "symbols" },
  { emoji: "☑️", name: "check box with check", category: "symbols" },
  { emoji: "✔️", name: "check mark", category: "symbols" },
  { emoji: "✖️", name: "multiply", category: "symbols" },
  { emoji: "➕", name: "plus", category: "symbols" },
  { emoji: "➖", name: "minus", category: "symbols" },
  { emoji: "➗", name: "divide", category: "symbols" },
  { emoji: "♾️", name: "infinity", category: "symbols" },
  { emoji: "‼️", name: "double exclamation mark", category: "symbols" },
  { emoji: "⁉️", name: "exclamation question mark", category: "symbols" },
  { emoji: "❓", name: "question mark", category: "symbols" },
  { emoji: "❔", name: "white question mark", category: "symbols" },
  { emoji: "❕", name: "white exclamation mark", category: "symbols" },
  { emoji: "❗", name: "exclamation mark", category: "symbols" },
  { emoji: "〰️", name: "wavy dash", category: "symbols" },
  { emoji: "💱", name: "currency exchange", category: "symbols" },
  { emoji: "💲", name: "heavy dollar sign", category: "symbols" },
  { emoji: "⚕️", name: "medical symbol", category: "symbols" },
  { emoji: "♻️", name: "recycling symbol", category: "symbols" },
  { emoji: "⚜️", name: "fleur de lis", category: "symbols" },
  { emoji: "🔱", name: "trident emblem", category: "symbols" },
  { emoji: "📛", name: "name badge", category: "symbols" },
  { emoji: "🔰", name: "japanese symbol for beginner", category: "symbols" },
  { emoji: "🌠", name: "shooting star", category: "symbols" },
  { emoji: "🔴", name: "red circle", category: "symbols" },
  { emoji: "🟠", name: "orange circle", category: "symbols" },
  { emoji: "🟡", name: "yellow circle", category: "symbols" },
  { emoji: "🟢", name: "green circle", category: "symbols" },
  { emoji: "🔵", name: "blue circle", category: "symbols" },
  { emoji: "🟣", name: "purple circle", category: "symbols" },
  { emoji: "🟤", name: "brown circle", category: "symbols" },
  { emoji: "⚫", name: "black circle", category: "symbols" },
  { emoji: "⚪", name: "white circle", category: "symbols" },
  { emoji: "🟥", name: "red square", category: "symbols" },
  { emoji: "🟧", name: "orange square", category: "symbols" },
  { emoji: "🟨", name: "yellow square", category: "symbols" },
  { emoji: "🟩", name: "green square", category: "symbols" },
  { emoji: "🟦", name: "blue square", category: "symbols" },
  { emoji: "🟪", name: "purple square", category: "symbols" },
  { emoji: "🟫", name: "brown square", category: "symbols" },
  { emoji: "⬛", name: "black large square", category: "symbols" },
  { emoji: "⬜", name: "white large square", category: "symbols" },
  { emoji: "🔶", name: "large orange diamond", category: "symbols" },
  { emoji: "🔷", name: "large blue diamond", category: "symbols" },
  { emoji: "🔸", name: "small orange diamond", category: "symbols" },
  { emoji: "🔹", name: "small blue diamond", category: "symbols" },
  { emoji: "🔺", name: "red triangle pointed up", category: "symbols" },
  { emoji: "🔻", name: "red triangle pointed down", category: "symbols" },
  { emoji: "💠", name: "diamond with a dot", category: "symbols" },

  // Animals (80 emojis)
  { emoji: "🐶", name: "dog face", category: "animals" },
  { emoji: "🐱", name: "cat face", category: "animals" },
  { emoji: "🐭", name: "mouse face", category: "animals" },
  { emoji: "🐹", name: "hamster", category: "animals" },
  { emoji: "🐰", name: "rabbit face", category: "animals" },
  { emoji: "🦊", name: "fox", category: "animals" },
  { emoji: "🐻", name: "bear", category: "animals" },
  { emoji: "🐼", name: "panda", category: "animals" },
  { emoji: "🐨", name: "koala", category: "animals" },
  { emoji: "🐯", name: "tiger face", category: "animals" },
  { emoji: "🦁", name: "lion", category: "animals" },
  { emoji: "🐮", name: "cow face", category: "animals" },
  { emoji: "🐷", name: "pig face", category: "animals" },
  { emoji: "🐽", name: "pig nose", category: "animals" },
  { emoji: "🐸", name: "frog", category: "animals" },
  { emoji: "🐵", name: "monkey face", category: "animals" },
  { emoji: "🙈", name: "see no evil monkey", category: "animals" },
  { emoji: "🙉", name: "hear no evil monkey", category: "animals" },
  { emoji: "🙊", name: "speak no evil monkey", category: "animals" },
  { emoji: "🐒", name: "monkey", category: "animals" },
  { emoji: "🐔", name: "chicken", category: "animals" },
  { emoji: "🐧", name: "penguin", category: "animals" },
  { emoji: "🐦", name: "bird", category: "animals" },
  { emoji: "🐤", name: "baby chick", category: "animals" },
  { emoji: "🐣", name: "hatching chick", category: "animals" },
  { emoji: "🐥", name: "front facing baby chick", category: "animals" },
  { emoji: "🦆", name: "duck", category: "animals" },
  { emoji: "🦅", name: "eagle", category: "animals" },
  { emoji: "🦉", name: "owl", category: "animals" },
  { emoji: "🦇", name: "bat", category: "animals" },
  { emoji: "🐺", name: "wolf", category: "animals" },
  { emoji: "🐗", name: "boar", category: "animals" },
  { emoji: "🐴", name: "horse face", category: "animals" },
  { emoji: "🦄", name: "unicorn", category: "animals" },
  { emoji: "🐝", name: "honeybee", category: "animals" },
  { emoji: "🐛", name: "bug", category: "animals" },
  { emoji: "🦋", name: "butterfly", category: "animals" },
  { emoji: "🐌", name: "snail", category: "animals" },
  { emoji: "🐞", name: "lady beetle", category: "animals" },
  { emoji: "🐜", name: "ant", category: "animals" },
  { emoji: "🦗", name: "cricket", category: "animals" },
  { emoji: "🕷️", name: "spider", category: "animals" },
  { emoji: "🕸️", name: "spider web", category: "animals" },
  { emoji: "🦂", name: "scorpion", category: "animals" },
  { emoji: "🐢", name: "turtle", category: "animals" },
  { emoji: "🐍", name: "snake", category: "animals" },
  { emoji: "🦎", name: "lizard", category: "animals" },
  { emoji: "🦖", name: "t rex", category: "animals" },
  { emoji: "🦕", name: "sauropod", category: "animals" },
  { emoji: "🐙", name: "octopus", category: "animals" },
  { emoji: "🦑", name: "squid", category: "animals" },
  { emoji: "🦐", name: "shrimp", category: "animals" },
  { emoji: "🦞", name: "lobster", category: "animals" },
  { emoji: "🦀", name: "crab", category: "animals" },
  { emoji: "🐡", name: "blowfish", category: "animals" },
  { emoji: "🐠", name: "tropical fish", category: "animals" },
  { emoji: "🐟", name: "fish", category: "animals" },
  { emoji: "🐬", name: "dolphin", category: "animals" },
  { emoji: "🐳", name: "spouting whale", category: "animals" },
  { emoji: "🐋", name: "whale", category: "animals" },
  { emoji: "🦈", name: "shark", category: "animals" },
  { emoji: "🐊", name: "crocodile", category: "animals" },
  { emoji: "🐅", name: "tiger", category: "animals" },
  { emoji: "🐆", name: "leopard", category: "animals" },
  { emoji: "🦓", name: "zebra", category: "animals" },
  { emoji: "🦍", name: "gorilla", category: "animals" },
  { emoji: "🦧", name: "orangutan", category: "animals" },
  { emoji: "🐘", name: "elephant", category: "animals" },
  { emoji: "🦛", name: "hippopotamus", category: "animals" },
  { emoji: "🦏", name: "rhinoceros", category: "animals" },
  { emoji: "🐪", name: "camel", category: "animals" },
  { emoji: "🐫", name: "two hump camel", category: "animals" },
  { emoji: "🦒", name: "giraffe", category: "animals" },
  { emoji: "🦘", name: "kangaroo", category: "animals" },
  { emoji: "🐃", name: "water buffalo", category: "animals" },
  { emoji: "🐂", name: "ox", category: "animals" },
  { emoji: "🐄", name: "cow", category: "animals" },
  { emoji: "🐎", name: "horse", category: "animals" },
  { emoji: "🐖", name: "pig", category: "animals" },
  { emoji: "🐏", name: "ram", category: "animals" },

  // Food (80 emojis)
  { emoji: "🍇", name: "grapes", category: "food" },
  { emoji: "🍈", name: "melon", category: "food" },
  { emoji: "🍉", name: "watermelon", category: "food" },
  { emoji: "🍊", name: "tangerine", category: "food" },
  { emoji: "🍋", name: "lemon", category: "food" },
  { emoji: "🍌", name: "banana", category: "food" },
  { emoji: "🍍", name: "pineapple", category: "food" },
  { emoji: "🥭", name: "mango", category: "food" },
  { emoji: "🍎", name: "red apple", category: "food" },
  { emoji: "🍏", name: "green apple", category: "food" },
  { emoji: "🍐", name: "pear", category: "food" },
  { emoji: "🍑", name: "peach", category: "food" },
  { emoji: "🍒", name: "cherries", category: "food" },
  { emoji: "🍓", name: "strawberry", category: "food" },
  { emoji: "🥝", name: "kiwi fruit", category: "food" },
  { emoji: "🍅", name: "tomato", category: "food" },
  { emoji: "🥥", name: "coconut", category: "food" },
  { emoji: "🥑", name: "avocado", category: "food" },
  { emoji: "🍆", name: "eggplant", category: "food" },
  { emoji: "🥔", name: "potato", category: "food" },
  { emoji: "🥕", name: "carrot", category: "food" },
  { emoji: "🌽", name: "ear of corn", category: "food" },
  { emoji: "🌶️", name: "hot pepper", category: "food" },
  { emoji: "🥒", name: "cucumber", category: "food" },
  { emoji: "🥬", name: "leafy green", category: "food" },
  { emoji: "🥦", name: "broccoli", category: "food" },
  { emoji: "🧄", name: "garlic", category: "food" },
  { emoji: "🧅", name: "onion", category: "food" },
  { emoji: "🍄", name: "mushroom", category: "food" },
  { emoji: "🥜", name: "peanuts", category: "food" },
  { emoji: "🌰", name: "chestnut", category: "food" },
  { emoji: "🍞", name: "bread", category: "food" },
  { emoji: "🥐", name: "croissant", category: "food" },
  { emoji: "🥖", name: "baguette bread", category: "food" },
  { emoji: "🥨", name: "pretzel", category: "food" },
  { emoji: "🥯", name: "bagel", category: "food" },
  { emoji: "🥞", name: "pancakes", category: "food" },
  { emoji: "🧇", name: "waffle", category: "food" },
  { emoji: "🧀", name: "cheese wedge", category: "food" },
  { emoji: "🍖", name: "meat on bone", category: "food" },
  { emoji: "🍗", name: "poultry leg", category: "food" },
  { emoji: "🥩", name: "cut of meat", category: "food" },
  { emoji: "🥓", name: "bacon", category: "food" },
  { emoji: "🍔", name: "hamburger", category: "food" },
  { emoji: "🍟", name: "french fries", category: "food" },
  { emoji: "🍕", name: "pizza", category: "food" },
  { emoji: "🌭", name: "hot dog", category: "food" },
  { emoji: "🥪", name: "sandwich", category: "food" },
  { emoji: "🌮", name: "taco", category: "food" },
  { emoji: "🌯", name: "burrito", category: "food" },
  { emoji: "🥙", name: "stuffed flatbread", category: "food" },
  { emoji: "🧆", name: "falafel", category: "food" },
  { emoji: "🥚", name: "egg", category: "food" },
  { emoji: "🍳", name: "cooking", category: "food" },
  { emoji: "🥘", name: "shallow pan of food", category: "food" },
  { emoji: "🍲", name: "pot of food", category: "food" },
  { emoji: "🥣", name: "bowl with spoon", category: "food" },
  { emoji: "🥗", name: "green salad", category: "food" },
  { emoji: "🍿", name: "popcorn", category: "food" },
  { emoji: "🧈", name: "butter", category: "food" },
  { emoji: "🧂", name: "salt", category: "food" },
  { emoji: "🥫", name: "canned food", category: "food" },
  { emoji: "🍱", name: "bento box", category: "food" },
  { emoji: "🍘", name: "rice cracker", category: "food" },
  { emoji: "🍙", name: "rice ball", category: "food" },
  { emoji: "🍚", name: "cooked rice", category: "food" },
  { emoji: "🍛", name: "curry rice", category: "food" },
  { emoji: "🍜", name: "steaming bowl", category: "food" },
  { emoji: "🍝", name: "spaghetti", category: "food" },
  { emoji: "🍠", name: "roasted sweet potato", category: "food" },
  { emoji: "🍢", name: "oden", category: "food" },
  { emoji: "🍣", name: "sushi", category: "food" },
  { emoji: "🍤", name: "fried shrimp", category: "food" },
  { emoji: "🍥", name: "fish cake with swirl", category: "food" },
  { emoji: "🥮", name: "moon cake", category: "food" },
  { emoji: "🍡", name: "dango", category: "food" },
  { emoji: "🥟", name: "dumpling", category: "food" },
  { emoji: "🥠", name: "fortune cookie", category: "food" },
  { emoji: "🥡", name: "takeout box", category: "food" },

  // Travel (80 emojis)
  { emoji: "🚗", name: "automobile", category: "travel" },
  { emoji: "🚕", name: "taxi", category: "travel" },
  { emoji: "🚙", name: "sport utility vehicle", category: "travel" },
  { emoji: "🚌", name: "bus", category: "travel" },
  { emoji: "🚎", name: "trolleybus", category: "travel" },
  { emoji: "🏎️", name: "racing car", category: "travel" },
  { emoji: "🚓", name: "police car", category: "travel" },
  { emoji: "🚑", name: "ambulance", category: "travel" },
  { emoji: "🚒", name: "fire engine", category: "travel" },
  { emoji: "🚐", name: "minibus", category: "travel" },
  { emoji: "🚚", name: "delivery truck", category: "travel" },
  { emoji: "🚛", name: "articulated lorry", category: "travel" },
  { emoji: "🚜", name: "tractor", category: "travel" },
  { emoji: "🛴", name: "kick scooter", category: "travel" },
  { emoji: "🚲", name: "bicycle", category: "travel" },
  { emoji: "🛵", name: "motor scooter", category: "travel" },
  { emoji: "🏍️", name: "motorcycle", category: "travel" },
  { emoji: "🛺", name: "auto rickshaw", category: "travel" },
  { emoji: "🚨", name: "police car light", category: "travel" },
  { emoji: "🚔", name: "oncoming police car", category: "travel" },
  { emoji: "🚍", name: "oncoming bus", category: "travel" },
  { emoji: "🚘", name: "oncoming automobile", category: "travel" },
  { emoji: "🚖", name: "oncoming taxi", category: "travel" },
  { emoji: "🚡", name: "aerial tramway", category: "travel" },
  { emoji: "🚠", name: "mountain cableway", category: "travel" },
  { emoji: "🚟", name: "suspension railway", category: "travel" },
  { emoji: "🚃", name: "railway car", category: "travel" },
  { emoji: "🚋", name: "tram car", category: "travel" },
  { emoji: "🚞", name: "mountain railway", category: "travel" },
  { emoji: "🚝", name: "monorail", category: "travel" },
  { emoji: "🚄", name: "high speed train", category: "travel" },
  { emoji: "🚅", name: "bullet train", category: "travel" },
  { emoji: "🚈", name: "light rail", category: "travel" },
  { emoji: "🚂", name: "locomotive", category: "travel" },
  { emoji: "🚆", name: "train", category: "travel" },
  { emoji: "🚇", name: "metro", category: "travel" },
  { emoji: "🚊", name: "tram", category: "travel" },
  { emoji: "🚉", name: "station", category: "travel" },
  { emoji: "✈️", name: "airplane", category: "travel" },
  { emoji: "🛫", name: "airplane departure", category: "travel" },
  { emoji: "🛬", name: "airplane arrival", category: "travel" },
  { emoji: "🛩️", name: "small airplane", category: "travel" },
  { emoji: "💺", name: "seat", category: "travel" },
  { emoji: "🛰️", name: "satellite", category: "travel" },
  { emoji: "🚁", name: "helicopter", category: "travel" },
  { emoji: "🛸", name: "flying saucer", category: "travel" },
  { emoji: "🚀", name: "rocket", category: "travel" },
  { emoji: "🛶", name: "canoe", category: "travel" },
  { emoji: "⛵", name: "sailboat", category: "travel" },
  { emoji: "🚤", name: "speedboat", category: "travel" },
  { emoji: "🛥️", name: "motor boat", category: "travel" },
  { emoji: "🛳️", name: "passenger ship", category: "travel" },
  { emoji: "⛴️", name: "ferry", category: "travel" },
  { emoji: "🚢", name: "ship", category: "travel" },
  { emoji: "⚓", name: "anchor", category: "travel" },
  { emoji: "⛽", name: "fuel pump", category: "travel" },
  { emoji: "🚧", name: "construction", category: "travel" },
  { emoji: "🚦", name: "vertical traffic light", category: "travel" },
  { emoji: "🚥", name: "horizontal traffic light", category: "travel" },
  { emoji: "🗺️", name: "world map", category: "travel" },
  { emoji: "🗿", name: "moai", category: "travel" },
  { emoji: "🗽", name: "statue of liberty", category: "travel" },
  { emoji: "🗼", name: "tokyo tower", category: "travel" },
  { emoji: "🏰", name: "castle", category: "travel" },
  { emoji: "🏯", name: "japanese castle", category: "travel" },
  { emoji: "🏟️", name: "stadium", category: "travel" },
  { emoji: "🎡", name: "ferris wheel", category: "travel" },
  { emoji: "🎢", name: "roller coaster", category: "travel" },
  { emoji: "🎠", name: "carousel horse", category: "travel" },
  { emoji: "⛲", name: "fountain", category: "travel" },
  { emoji: "🏖️", name: "beach with umbrella", category: "travel" },
  { emoji: "🏝️", name: "desert island", category: "travel" },
  { emoji: "🏜️", name: "desert", category: "travel" },
  { emoji: "🌋", name: "volcano", category: "travel" },
  { emoji: "⛰️", name: "mountain", category: "travel" },
  { emoji: "🏔️", name: "snow capped mountain", category: "travel" },
  { emoji: "🗻", name: "mount fuji", category: "travel" },
  { emoji: "🏕️", name: "camping", category: "travel" },
  { emoji: "⛺", name: "tent", category: "travel" },

  // Activities (80 emojis)
  { emoji: "⚽", name: "soccer ball", category: "activities" },
  { emoji: "🏀", name: "basketball", category: "activities" },
  { emoji: "🏈", name: "american football", category: "activities" },
  { emoji: "⚾", name: "baseball", category: "activities" },
  { emoji: "🥎", name: "softball", category: "activities" },
  { emoji: "🎾", name: "tennis", category: "activities" },
  { emoji: "🏐", name: "volleyball", category: "activities" },
  { emoji: "🏉", name: "rugby football", category: "activities" },
  { emoji: "🥏", name: "flying disc", category: "activities" },
  { emoji: "🎱", name: "pool 8 ball", category: "activities" },
  { emoji: "🪀", name: "yo yo", category: "activities" },
  { emoji: "🏓", name: "ping pong", category: "activities" },
  { emoji: "🏸", name: "badminton", category: "activities" },
  { emoji: "🏒", name: "ice hockey", category: "activities" },
  { emoji: "🏑", name: "field hockey", category: "activities" },
  { emoji: "🥍", name: "lacrosse", category: "activities" },
  { emoji: "🏏", name: "cricket game", category: "activities" },
  { emoji: "🥅", name: "goal net", category: "activities" },
  { emoji: "⛳", name: "flag in hole", category: "activities" },
  { emoji: "🪁", name: "kite", category: "activities" },
  { emoji: "🏹", name: "bow and arrow", category: "activities" },
  { emoji: "🎣", name: "fishing pole", category: "activities" },
  { emoji: "🤿", name: "diving mask", category: "activities" },
  { emoji: "🥊", name: "boxing glove", category: "activities" },
  { emoji: "🥋", name: "martial arts uniform", category: "activities" },
  { emoji: "🎽", name: "running shirt", category: "activities" },
  { emoji: "🛹", name: "skateboard", category: "activities" },
  { emoji: "🛷", name: "sled", category: "activities" },
  { emoji: "⛸️", name: "ice skate", category: "activities" },
  { emoji: "🥌", name: "curling stone", category: "activities" },
  { emoji: "🎿", name: "skis", category: "activities" },
  { emoji: "⛷️", name: "skier", category: "activities" },
  { emoji: "🏂", name: "snowboarder", category: "activities" },
  { emoji: "🪂", name: "parachute", category: "activities" },
  { emoji: "🏋️", name: "person lifting weights", category: "activities" },
  { emoji: "🤼", name: "people wrestling", category: "activities" },
  { emoji: "🤸", name: "person cartwheeling", category: "activities" },
  { emoji: "⛹️", name: "person bouncing ball", category: "activities" },
  { emoji: "🤺", name: "person fencing", category: "activities" },
  { emoji: "🤾", name: "person playing handball", category: "activities" },
  { emoji: "🏌️", name: "person golfing", category: "activities" },
  { emoji: "🏇", name: "horse racing", category: "activities" },
  { emoji: "🧘", name: "person in lotus position", category: "activities" },
  { emoji: "🏄", name: "person surfing", category: "activities" },
  { emoji: "🏊", name: "person swimming", category: "activities" },
  { emoji: "🤽", name: "person playing water polo", category: "activities" },
  { emoji: "🚣", name: "person rowing boat", category: "activities" },
  { emoji: "🧗", name: "person climbing", category: "activities" },
  { emoji: "🚵", name: "person mountain biking", category: "activities" },
  { emoji: "🚴", name: "person biking", category: "activities" },
  { emoji: "🎪", name: "circus tent", category: "activities" },
  { emoji: "🎭", name: "performing arts", category: "activities" },
  { emoji: "🎨", name: "artist palette", category: "activities" },
  { emoji: "🎤", name: "microphone", category: "activities" },
  { emoji: "🎧", name: "headphone", category: "activities" },
  { emoji: "🎼", name: "musical score", category: "activities" },
  { emoji: "🎹", name: "musical keyboard", category: "activities" },
  { emoji: "🥁", name: "drum", category: "activities" },
  { emoji: "🎷", name: "saxophone", category: "activities" },
  { emoji: "🎺", name: "trumpet", category: "activities" },
  { emoji: "🎸", name: "guitar", category: "activities" },
  { emoji: "🪕", name: "banjo", category: "activities" },
  { emoji: "🎻", name: "violin", category: "activities" },
  { emoji: "🎲", name: "game die", category: "activities" },
  { emoji: "♟️", name: "chess pawn", category: "activities" },
  { emoji: "🎯", name: "direct hit", category: "activities" },
  { emoji: "🎳", name: "bowling", category: "activities" },
  { emoji: "🎮", name: "video game", category: "activities" },
  { emoji: "🎰", name: "slot machine", category: "activities" },
  { emoji: "🧩", name: "puzzle piece", category: "activities" },
  { emoji: "🧵", name: "thread", category: "activities" },
  { emoji: "🪡", name: "sewing needle", category: "activities" },
  { emoji: "🧶", name: "yarn", category: "activities" },
  { emoji: "🪢", name: "knot", category: "activities" },
];

export const CATEGORIES = [
  "smileys",
  "objects",
  "symbols",
  "animals",
  "food",
  "travel",
  "activities",
] as const;
